package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.64

import (
	"context"
	"fmt"

	"github.com/invalidopc0de/redata-server/graph/model"
)

// CreateSystem is the resolver for the createSystem field.
func (r *mutationResolver) CreateSystem(ctx context.Context, input model.NewSystem) (*model.System, error) {
	panic(fmt.Errorf("not implemented: CreateSystem - createSystem"))
}

// Systems is the resolver for the systems field.
func (r *queryResolver) Systems(ctx context.Context) ([]*model.System, error) {
	panic(fmt.Errorf("not implemented: Systems - systems"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
