apiVersion: v1
kind: Service
metadata:
  name: minio-api
  namespace: redata
spec:
  type: ClusterIP
  ports:
    - port: 9000
  selector:
    app: minio
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-init
  labels:
    app: minio
  namespace: redata
data:
  start-minio.sh: |
    #!/usr/bin/env bash
    minio server /data --console-address :9090 &

    sleep 5

    /usr/bin/mc config host add minio_inst http://minio:9000 $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
    /usr/bin/mc mb --with-lock minio_inst/redata-blob-storage
    /usr/bin/mc mb --with-lock minio_inst/redata-timeseres-storage

    while true; do sleep 1; done;
---
apiVersion: v1
kind: Service
metadata:
  name: minio-web
  namespace: redata
spec:
  type: ClusterIP
  ports:
    - port: 9090
  selector:
    app: minio
---
# Deploys a new MinIO Pod into the metadata.namespace Kubernetes namespace
#
# The `spec.containers[0].args` contains the command run on the pod
# The `/data` directory corresponds to the `spec.containers[0].volumeMounts[0].mountPath`
# That mount path corresponds to a Kubernetes HostPath which binds `/data` to a local drive or volume on the worker node where the pod runs
#
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: minio
  name: minio
  namespace: redata # Change this value to match the namespace metadata.name
spec:
  serviceName: "minio"
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: quay.io/minio/minio:latest
          command:
            - /bin/bash
            - -c
          args:
            - bash /minio-init/start-minio.sh
          env:
            - name: MINIO_ACCESS_KEY
              value: xl9pfuASxMm2cKEXkfdD
            - name: MINIO_SECRET_KEY
              value: Ai0R3O569JVT5JOM3cLHBg9T6O4MXyvrCwTTIBhR
          volumeMounts:
            - mountPath: /data
              name: localvolume # Corresponds to the `spec.volumes` Persistent Volume
            - name: minio-init
              mountPath: "/minio-init"
              readOnly: true
          ports:
            - containerPort: 9000
            - containerPort: 9090
      volumes:
        - name: localvolume
          hostPath: # MinIO generally recommends using locally-attached volumes
            path: /var/lib/minikube/minio # Specify a path to a local drive or volume on the Kubernetes worker node
            type: DirectoryOrCreate # The path to the last directory must exist
        - name: minio-init
          configMap:
            name: minio-init
