apiVersion: v1
kind: ConfigMap
metadata:
  name: redata-config
data:
  redata.yaml: |
    trino:
      host: http://trino
      port: 8080
      username: admin
      password: "" # Default trino doesn't have a real auth setup
    s3:
      endpoint: http://minio-api:9000
      region: us-east-1
      bucket: redata-blob-storage
      access_key: xl9pfuASxMm2cKEXkfdD
      secret_key: Ai0R3O569JVT5JOM3cLHBg9T6O4MXyvrCwTTIBhR
---
apiVersion: v1
kind: Service
metadata:
  name: redata
  namespace: redata
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    app: redata
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redata
  labels:
    app: redata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redata
  template:
    metadata:
      name: redata
      labels:
        app: redata
    spec:
      containers:
        - name: redata
          image: redata
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: redata-config
              mountPath: "/etc/redata"
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: redata-config
          configMap:
            name: redata-config
