apiVersion: v1
kind: Service
metadata:
  name: redata
  namespace: redata
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    app: redata
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redata
  labels:
    app: redata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redata
  template:
    metadata:
      name: redata
      labels:
        app: redata
    spec:
      containers:
        - name: redata
          image: redata
          imagePullPolicy: Never
#          ports:
#            - containerPort: 80
#              protocol: TCP
      restartPolicy: Always
