// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BlobParent interface {
	IsBlobParent()
}

type Blob struct {
	ID           string     `json:"id"`
	Parent       BlobParent `json:"parent"`
	Name         string     `json:"name"`
	DataLocation string     `json:"data_location"`
}

type Mutation struct {
}

type NewSystem struct {
	Name string `json:"name"`
}

type Query struct {
}

type Run struct {
	ID     string  `json:"id"`
	System *System `json:"system"`
}

func (Run) IsBlobParent() {}

type RunProperty struct {
	ID    string `json:"id"`
	Run   *Run   `json:"run"`
	Name  string `json:"name"`
	Value string `json:"value"`
}

type RunTag struct {
	ID    string `json:"id"`
	Run   *Run   `json:"run"`
	Value string `json:"value"`
}

type System struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (System) IsBlobParent() {}
